apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nova-rewards
  namespace: nova-rewards
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nova-rewards.io
      secretName: nova-rewards-tls
  rules:
    - host: nova-rewards.io
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nova-rewards-backend
                port:
                  number: 80
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nova-rewards-frontend
                port:
                  number: 80
