#![cfg(test)]

use nova_token::NovaToken;
use soroban_sdk::{testutils::Address as _, Address, Env};

// ── client generated by soroban-sdk macro ────────────────────────────────────
use nova_token::NovaTokenClient;

fn setup() -> (Env, Address, NovaTokenClient<'static>) {
    let env = Env::default();
    env.mock_all_auths();
    let id = env.register(NovaToken, ());
    let client = NovaTokenClient::new(&env, &id);
    let admin = Address::generate(&env);
    client.initialize(&admin);
    (env, admin, client)
}

// ── initialize ────────────────────────────────────────────────────────────────

#[test]
fn initialize_sets_admin() {
    let (_env, _admin, _client) = setup(); // no panic = success
}

#[test]
#[should_panic(expected = "already initialised")]
fn initialize_twice_panics() {
    let (env, admin, client) = setup();
    client.initialize(&admin); // second call must panic
}

// ── balance ───────────────────────────────────────────────────────────────────

#[test]
fn balance_of_unknown_address_is_zero() {
    let (env, _admin, client) = setup();
    let stranger = Address::generate(&env);
    assert_eq!(client.balance(&stranger), 0);
}

// ── mint ──────────────────────────────────────────────────────────────────────

#[test]
fn mint_increases_balance() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &1_000);
    assert_eq!(client.balance(&user), 1_000);
}

#[test]
fn mint_accumulates_across_calls() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &500);
    client.mint(&user, &300);
    assert_eq!(client.balance(&user), 800);
}

#[test]
#[should_panic(expected = "amount must be positive")]
fn mint_zero_panics() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &0);
}

#[test]
#[should_panic(expected = "amount must be positive")]
fn mint_negative_panics() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &-1);
}

// ── burn ──────────────────────────────────────────────────────────────────────

#[test]
fn burn_decreases_balance() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &1_000);
    client.burn(&user, &400);
    assert_eq!(client.balance(&user), 600);
}

#[test]
fn burn_entire_balance_leaves_zero() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &100);
    client.burn(&user, &100);
    assert_eq!(client.balance(&user), 0);
}

#[test]
#[should_panic(expected = "insufficient balance")]
fn burn_more_than_balance_panics() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &50);
    client.burn(&user, &51);
}

#[test]
#[should_panic(expected = "amount must be positive")]
fn burn_zero_panics() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.mint(&user, &100);
    client.burn(&user, &0);
}

#[test]
#[should_panic(expected = "insufficient balance")]
fn burn_from_empty_account_panics() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    client.burn(&user, &1);
}

// ── transfer ──────────────────────────────────────────────────────────────────

#[test]
fn transfer_moves_tokens() {
    let (env, _admin, client) = setup();
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    client.mint(&alice, &1_000);
    client.transfer(&alice, &bob, &300);
    assert_eq!(client.balance(&alice), 700);
    assert_eq!(client.balance(&bob), 300);
}

#[test]
fn transfer_full_balance() {
    let (env, _admin, client) = setup();
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    client.mint(&alice, &500);
    client.transfer(&alice, &bob, &500);
    assert_eq!(client.balance(&alice), 0);
    assert_eq!(client.balance(&bob), 500);
}

#[test]
#[should_panic(expected = "insufficient balance")]
fn transfer_more_than_balance_panics() {
    let (env, _admin, client) = setup();
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    client.mint(&alice, &100);
    client.transfer(&alice, &bob, &101);
}

#[test]
#[should_panic(expected = "amount must be positive")]
fn transfer_zero_panics() {
    let (env, _admin, client) = setup();
    let alice = Address::generate(&env);
    let bob = Address::generate(&env);
    client.mint(&alice, &100);
    client.transfer(&alice, &bob, &0);
}

// ── approve / allowance ───────────────────────────────────────────────────────

#[test]
fn approve_sets_allowance() {
    let (env, _admin, client) = setup();
    let owner = Address::generate(&env);
    let spender = Address::generate(&env);
    client.approve(&owner, &spender, &2_000);
    assert_eq!(client.allowance(&owner, &spender), 2_000);
}

#[test]
fn allowance_of_unknown_pair_is_zero() {
    let (env, _admin, client) = setup();
    let owner = Address::generate(&env);
    let spender = Address::generate(&env);
    assert_eq!(client.allowance(&owner, &spender), 0);
}

#[test]
fn approve_overwrites_previous_allowance() {
    let (env, _admin, client) = setup();
    let owner = Address::generate(&env);
    let spender = Address::generate(&env);
    client.approve(&owner, &spender, &500);
    client.approve(&owner, &spender, &1_500);
    assert_eq!(client.allowance(&owner, &spender), 1_500);
}

#[test]
fn approve_zero_clears_allowance() {
    let (env, _admin, client) = setup();
    let owner = Address::generate(&env);
    let spender = Address::generate(&env);
    client.approve(&owner, &spender, &1_000);
    client.approve(&owner, &spender, &0);
    assert_eq!(client.allowance(&owner, &spender), 0);
}

// ── boundary: large values ────────────────────────────────────────────────────

#[test]
fn mint_and_burn_large_amount() {
    let (env, _admin, client) = setup();
    let user = Address::generate(&env);
    let large: i128 = i128::MAX / 2;
    client.mint(&user, &large);
    assert_eq!(client.balance(&user), large);
    client.burn(&user, &large);
    assert_eq!(client.balance(&user), 0);
}
